termcase.settings:
  type: config_object
  mapping:
    termcase_settings:
      type: fieldset
      label: 'Term case settings'
    termcase_options:
      type: select
      label: 'Convert terms to this case'
    termcase_update_terms:
      type: checkbox
      label: 'Convert the existing terms in this vocabulary immediately'
